#!/bin/sh

# video_res=$(xdpyinfo | awk '/dimensions/{print $2}')
video_res=$(xrandr | grep '*' -m 1 | awk '{ print $1 }')

ffmpeg -video_size ${video_res} -framerate 25 -f x11grab -i ${DISPLAY} record.mp4
