#!/usr/bin/env sh

# Description: Run 'tig status' in dvtm
#
# Shell: POSIX compliant
# Authors: Vadym Kochan <vadimj@gmail.com>

if [ -z "${DVTM_CMD_FIFO}" ]; then
    tig status
else
    printf "create \"tig status\" \"git status\" \$CWD\n" > ${DVTM_CMD_FIFO}
fi
