#!/usr/bin/env sh

# Description: Open selected file in new DVTM window
#
# Shell: POSIX compliant
# Authors: Vadym Kochan <vadimj@gmail.com>

if [ -z "$EDITOR" ]; then
	echo 'ERROR: $EDITOR is not set' | ${PAGER:-less}
	exit 2
fi
if [ -z "$DVTM_CMD_FIFO" ]; then
	echo 'ERROR: $DVTM_CMD_FIFO is not set' | ${PAGER:-less}
	exit 2
fi

if [ -n "$2" ]; then
    dir="$2/"
else
    dir=""
fi

printf "create \"$EDITOR ${dir}${1}\" $(basename $1) \$CWD\n" > ${DVTM_CMD_FIFO}
