#!/bin/sh

export NNN_OPENER="${HOME}/.config/nnn/plugins/dvtm/open"
export NNN_PLUG="e:dvtm/editor;g:dvtm/git;f:dvtm/fzy-open;c:fzy-cd;x:dvtm/shell"
export PATH=${HOME}/repo/dvtm-vk:${PATH}

CMD_FIFO=/var/run/user/${UID}/dvtm-cmd

unlink ${CMD_FIFO}
mkfifo ${CMD_FIFO}

printf "setmfact 0.25\ncreate nnn\nsetsticky\n" > ${CMD_FIFO} &

${HOME}/repo/dvtm-vk/dvtm -c ${CMD_FIFO}
