#!/usr/bin/env sh

# Description: cd to directory selected by fzy
#
# Shell: POSIX compliant
# Author: Vadym Kochan

if [ -z "$NNN_PIPE" ]; then
	echo 'ERROR: $NNN_PIPE is not set' | ${PAGER:-less}
	exit 2
fi

sel=$(find -type d | fzy -s -l 20)

if [ -n "${sel}" ]; then
	path=$(readlink -f $sel)
	printf "0c$path" > "$NNN_PIPE"
fi
